name: "test action"

on:
  workflow_call:
    outputs:
      git-sha:
        type: string
        required: true
      git-ref:
        type: string
        required: true

jobs:
  align-build-information:
    runs-on: ubuntu-latest
    steps:

    - name: just echo
      run: |
        echo "ran it"
